# Generated by Django 2.0.13 on 2019-09-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='category',
            field=models.CharField(choices=[('RU', 'Russia'), ('UKR', 'Ukraine'), ('US', 'USA')], default='RU', max_length=100),
        ),
    ]
